
# html lang
language: zh

# github url
github: https://github.com/fanhua5

# main menu navigation
menu:
  首页: /
  关于: /about
  归档: /archives

# stylesheets loaded in the <head>
stylesheets:
- /dist/css/main.css

# scripts loaded in the end of the body
scripts:
- /dist/main.js

# background img url
backgroundImg: '/img/background.jpg'

# favicon img url
faviconImg: '/img/favicon.ico'

# author img url
authorImg: '/img/author.jpg'
